
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '<\x18\\cd\x143\x11\x0f\xeb{\x1aA\x88N\xa1'
    
_lr_action_items = {'QUOTE':([3,],[4,]),'RPAREN':([2,5,6,],[-2,6,-1,]),'NUMBER':([0,4,],[2,2,]),'LPAREN':([0,4,],[3,3,]),'$end':([1,2,6,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[1,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN QUOTE expression RPAREN','expression',4,'p_expression_quote','lisp.py',61),
  ('expression -> NUMBER','expression',1,'p_expression_number','lisp.py',75),
]
